import './style.css';
import {AudioBox} from './audio';
import {encounters,Encounter,Choice,Metrics} from './data';

const canvas=document.querySelector<HTMLCanvasElement>('#game')!,ctx=canvas.getContext('2d')!,ui=document.querySelector<HTMLDivElement>('#ui')!,touch=document.querySelector<HTMLDivElement>('#touch')!;
ctx.imageSmoothingEnabled=false;
type Mode='menu'|'game'|'results'; type NPC={name:string;role:string;x:number;y:number;color:string;ambient:string;done:number};
const audio=new AudioBox(), keys=new Set<string>(), reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const obstacles=[{x:38,y:46,w:76,h:25},{x:145,y:43,w:75,h:25},{x:271,y:43,w:73,h:25},{x:56,y:125,w:69,h:25},{x:167,y:121,w:80,h:31},{x:302,y:116,w:33,h:38}];
const npcs:NPC[]=[
 {name:'Tuğba',role:'Tasarım',x:72,y:82,color:'#e66a8a',ambient:'“QR yine bana bakıyor…”',done:0},
 {name:'Sinan',role:'Backend',x:181,y:82,color:'#63c5da',ambient:'“Bu para nereye gitti?”',done:0},
 {name:'Berke',role:'DevOps',x:294,y:84,color:'#77c66e',ambient:'“Sunucu şıkırdıyor…”',done:0},
 {name:'Öykü',role:'Product',x:91,y:167,color:'#f3a953',ambient:'“Bol kazançlar yeter mi?”',done:0},
 {name:'Funda',role:'Ürün Müdürü',x:260,y:172,color:'#b48ee0',ambient:'“Roadmap telepatik oldu…”',done:0},
 {name:'Can',role:'Finans',x:340,y:177,color:'#df6f66',ambient:'“Hayaletin vergi no’su?”',done:0}
];
let mode:Mode='menu',paused=false;
let player={x:195,y:100,dir:1,walk:0};
let metrics:Metrics={cash:500,revenue:200,quality:60,morale:70},initial={...metrics},elapsed=0;
const completed=new Set<string>();
let grades={good:0,questionable:0,disaster:0};
let dialogue:null|{enc:Encounter;shown:number;reaction?:string}=null;
let floaters:{text:string;x:number;y:number;color:string;t:number}[]=[],shake=0,last=performance.now();

function button(label:string,action:()=>void,cls='pixel-btn'){const b=document.createElement('button');b.className=cls;b.textContent=label;b.onclick=()=>{audio.blip();action()};return b}
function menu(){mode='menu';touch.classList.remove('game-on');ui.innerHTML='';const s=document.createElement('section');s.className='screen';s.innerHTML='<h1 class="title">CTO:<br>SALÇA OLMA<br>SİMÜLATÖRÜ</h1><p class="subtitle">E-Para A.Ş. · Bir fikrin var. Herkesin haberi olacak.</p>';const m=document.createElement('div');m.className='menu';m.append(button('▶ OYNA',start),button('? NASIL OYNANIR',help),button(audio.muted?'🔇 SES: KAPALI':'🔊 SES: AÇIK',()=>{audio.toggle();menu()}));s.append(m);s.insertAdjacentHTML('beforeend','<p class="small">Bir Pikselli Kurumsal Müdahale Deneyimi</p>');ui.append(s)}
function help(){ui.innerHTML='';const s=document.createElement('section');s.className='screen help';s.innerHTML='<h2>NASIL SALÇA OLUNUR?</h2><p><b>WASD / Oklar</b> ile ofiste dolaş.<br><b>E / Boşluk</b> ile yakındaki ekip arkadaşına fikrini anlat.<br><b>Esc</b> ile duraklat.</p><p>8 kararda Kasa, Gelir, Kalite ve Morali dengede tut. Aynı kişiyle birden fazla kez konuşabilirsin. Telefonda ekrandaki tuşları kullan.</p>';s.append(button('← ANA MENÜ',menu));ui.append(s)}
function start(){mode='game';paused=false;player={x:195,y:100,dir:1,walk:0};metrics={...initial};elapsed=0;completed.clear();grades={good:0,questionable:0,disaster:0};dialogue=null;floaters=[];npcs.forEach(n=>n.done=0);touch.classList.add('game-on');renderUI()}
const money=(v:number)=>`₺${Math.round(v).toLocaleString('tr-TR')}K`;
function renderUI(){if(mode!=='game')return;ui.innerHTML=`<div class="hud"><div class="metric">💰 KASA <b>${money(metrics.cash)}</b></div><div class="metric">📈 GELİR <b>${money(metrics.revenue)}</b></div><div class="metric">◆ KALİTE <b>${metrics.quality}</b></div><div class="metric">♥ MORAL <b>${metrics.morale}</b></div><div class="metric timer">☕ ${Math.max(0,300-Math.floor(elapsed)).toString().replace(/^([0-9]+)$/,v=>`${Math.floor(+v/60)}:${String(+v%60).padStart(2,'0')}`)}</div></div>`;if(dialogue)drawDialogue();else {const n=nearNPC();if(n){const p=document.createElement('div');p.className='prompt';p.textContent='E / BOŞLUK: KONUŞ';ui.append(p)}}if(paused){const p=document.createElement('div');p.className='paused';p.innerHTML='<div>⏸ DURAKLATILDI<br><small>Devam etmek için ESC</small></div>';ui.append(p)}}
function nextEncounter(n:NPC){return encounters.find(e=>e.npc===n.name&&!completed.has(e.id))}
function nearNPC(){return npcs.find(n=>nextEncounter(n)&&Math.hypot(player.x-n.x,player.y-n.y)<27)}
function interact(){if(mode!=='game'||paused)return;if(dialogue){if(!dialogue.reaction&&dialogue.shown<dialogue.enc.prompt.length)dialogue.shown=dialogue.enc.prompt.length;return}const n=nearNPC();if(!n)return;const enc=nextEncounter(n);if(enc){dialogue={enc,shown:0};audio.pop();renderUI()}}
function drawDialogue(){const d=dialogue!,panel=document.createElement('section');panel.className='dialogue';const text=d.reaction??d.enc.prompt;panel.innerHTML=`<div class="speaker">${d.enc.npc} · ${d.enc.role}</div><p class="line">${text.slice(0,Math.floor(d.shown))}${d.shown<text.length?' ▮':''}</p>`;if(d.reaction&&d.shown>=text.length){panel.append(button('DEVAM ET ▸',closeDialogue))}else if(!d.reaction&&d.shown>=text.length){const cs=document.createElement('div');cs.className='choices';d.enc.choices.forEach(c=>cs.append(button(c.text,()=>choose(c),'choice')));panel.append(cs)}ui.append(panel)}
function choose(c:Choice){if(!dialogue)return;const before={...metrics};for(const k of Object.keys(c.effects) as (keyof Metrics)[])metrics[k]+=c.effects[k]!;metrics.quality=Math.max(0,Math.min(100,metrics.quality));metrics.morale=Math.max(0,Math.min(100,metrics.morale));grades[c.grade]++;completed.add(dialogue.enc.id);const n=npcs.find(n=>n.name===dialogue!.enc.npc)!;n.done++;Object.entries(c.effects).forEach(([k,v],i)=>floaters.push({text:`${{cash:'Kasa',revenue:'Gelir',quality:'Kalite',morale:'Moral'}[k as keyof Metrics]} ${(v as number)>0?'+':''}${k==='cash'||k==='revenue'?'₺':''}${v}${k==='cash'||k==='revenue'?'K':''}`,x:n.x-15,y:n.y-16-i*7,color:(v as number)>=0?'#78e08f':'#ff6b76',t:2}));if(c.grade==='good')audio.good();else if(c.grade==='disaster'){audio.bad();shake=reduced?0:7}else audio.pop();dialogue.reaction=c.reaction;dialogue.shown=0;if(before.cash<metrics.cash)audio.cash();renderUI()}
function closeDialogue(){dialogue=null;if(completed.size>=encounters.length||metrics.cash<=0||metrics.revenue<=0)finish();else renderUI()}
function finish(){mode='results';touch.classList.remove('game-on');dialogue=null;const profit=metrics.revenue-120+Math.round((metrics.quality-50)*.7+(metrics.morale-50)*.4);/* Fictional valuation formula: cash + 12×monthly revenue, multiplied by quality and morale health factors. */const valuation=Math.max(0,Math.round((metrics.cash+metrics.revenue*12)*(.5+metrics.quality/200)*(.6+metrics.morale/250)));const strong=profit>140&&metrics.quality>=65&&metrics.morale>=55&&metrics.cash>300;const dead=metrics.cash<=0||metrics.revenue<=50||metrics.quality<20||metrics.morale<20;const title=dead?'ŞİRKET BATTI':strong?'ŞİRKET UÇUŞA GEÇTİ':'BİR ŞEKİLDE AYAKTAYIZ';if(dead)audio.bankrupt();else if(strong)audio.cash();let summary=dead?'Şirket battı; ama sunumdaki roket animasyonu kusursuzdu.':strong?'Ekip seni Slack’te sessize almadı. Bu, kurumsal dünyada gerçek sevgidir.':'Rakamlar yaşıyor, ekip kahveyle. Pazartesiye kadar başarı sayılır.';if(completed.has('qr-pigeon')&&grades.disaster)summary+=' En azından QR güvercini hâlâ vizyoner.';ui.innerHTML='';const s=document.createElement('section');s.className='screen';s.innerHTML=`<h1 class="title">${title}</h1><div class="results"><div class="result-card">Kasa<br><b>${money(metrics.cash)}</b></div><div class="result-card">Aylık Gelir<br><b>${money(metrics.revenue)}</b></div><div class="result-card">Kâr / Zarar<br><b>${profit>=0?'+':''}${money(profit)}</b></div><div class="result-card">Şirket Değeri<br><b>${money(valuation)}</b></div><div class="result-card">Ürün Kalitesi<br><b>${metrics.quality}/100</b></div><div class="result-card">Ekip Morali<br><b>${metrics.morale}/100</b></div></div><p class="summary">${summary}</p><p class="small">✓ ${grades.good} sağduyulu · ~ ${grades.questionable} tartışmalı · ✕ ${grades.disaster} felaket</p>`;const m=document.createElement('div');m.className='menu';m.append(button('↻ TEKRAR OYNA',start),button('⌂ ANA MENÜ',menu));s.append(m);ui.append(s)}

function rect(x:number,y:number,w:number,h:number,c:string){ctx.fillStyle=c;ctx.fillRect(x,y,w,h)}
function office(){rect(0,0,384,216,'#d7bc83');for(let y=0;y<216;y+=16)for(let x=(y/16%2)*8;x<384;x+=16)rect(x,y,8,1,'#c3a66f');rect(0,0,384,28,'#48567b');rect(9,8,50,13,'#8bd3dd');rect(13,11,42,7,'#c4f1ed');rect(231,6,49,17,'#252c47');ctx.fillStyle='#ffd866';ctx.font='bold 7px monospace';ctx.fillText('E-PARA A.Ş.',237,17); // desks
 obstacles.forEach((o,i)=>{rect(o.x,o.y,o.w,o.h,i===4?'#8c6b58':'#755548');rect(o.x+2,o.y+2,o.w-4,4,'#b78361')});
 [[53,43],[160,40],[287,40]].forEach(([x,y])=>{rect(x,y,22,12,'#202943');rect(x+3,y+2,16,7,'#64c5da');rect(x+9,y+12,4,4,'#303752')});
 // meeting table, plant, coffee machine, rug
 ctx.fillStyle='#a9856a';ctx.beginPath();ctx.ellipse(207,136,36,14,0,0,7);ctx.fill();rect(310,120,18,27,'#d8dde8');rect(313,124,12,8,'#343c58');rect(316,134,6,5,'#d47b5e');rect(14,158,27,38,'#5c4774');for(let i=0;i<5;i++){rect(21+i*3,153-(i%2)*5,3,17,'#4b9b69')}rect(17,170,18,13,'#b65b57');rect(136,167,80,35,'#b786b9');rect(139,170,74,29,'#855f91')}
function character(x:number,y:number,color:string,cto=false,walk=0){const bob=!reduced&&Math.sin(walk*10)>0?1:0;rect(x-5,y-13-bob,10,8,cto?'#e4b28d':'#dca37c');rect(x-6,y-5-bob,12,10,color);rect(x-5,y+5,4,6,'#25263b');rect(x+2,y+5,4,6,'#25263b');rect(x-4,y-11-bob,2,2,'#24263a');rect(x+2,y-11-bob,2,2,'#24263a');if(cto){rect(x-6,y-12-bob,5,3,'#111526');rect(x+1,y-12-bob,5,3,'#111526');rect(x-1,y-11-bob,2,1,'#111526');rect(x-2,y-3-bob,4,5,'#ffd866');/* Eminem'in belirgin bordo CTO şapkası */rect(x-7,y-17-bob,14,3,'#6e2948');rect(x-5,y-21-bob,10,4,'#a43d60');rect(x+4,y-18-bob,6,2,'#d55b79')}}
function nameTag(name:string,x:number,y:number,playerName=false){ctx.textAlign='center';ctx.font='bold 7px monospace';const w=Math.ceil(ctx.measureText(name).width)+8;rect(Math.round(x-w/2),y-7,w,10,playerName?'#6e2948':'#171a2b');ctx.fillStyle=playerName?'#ffd866':'#fff';ctx.fillText(name,x,y)}
function render(){ctx.save();if(shake){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.85;if(shake<.2)shake=0}office();npcs.forEach(n=>{character(n.x,n.y,n.color,false,elapsed*.15);nameTag(n.name,n.x,n.y+21);if(n.done&&elapsed%4<1){rect(n.x-25,n.y-31,50,10,'#f4f1de');ctx.fillStyle='#20243b';ctx.font='5px monospace';ctx.fillText(n.ambient.slice(0,28),n.x,n.y-24)}});character(player.x,player.y,'#394b73',true,player.walk);nameTag('EMİNEM',player.x,player.y+21,true);floaters.forEach(f=>{ctx.fillStyle=f.color;ctx.font='bold 7px monospace';ctx.fillText(f.text,f.x,f.y)});ctx.restore()}
function blocked(x:number,y:number){return x<9||x>375||y<35||y>204||obstacles.some(o=>x+6>o.x&&x-6<o.x+o.w&&y+7>o.y&&y-10<o.y+o.h)}
function update(dt:number){if(mode!=='game'||paused||dialogue)return;elapsed+=dt;if(elapsed>=300){finish();return}let dx=0,dy=0;if(keys.has('left')||keys.has('arrowleft')||keys.has('a'))dx--;if(keys.has('right')||keys.has('arrowright')||keys.has('d'))dx++;if(keys.has('up')||keys.has('arrowup')||keys.has('w'))dy--;if(keys.has('down')||keys.has('arrowdown')||keys.has('s'))dy++;if(dx||dy){const l=Math.hypot(dx,dy),speed=55;dx=dx/l*speed*dt;dy=dy/l*speed*dt;if(!blocked(player.x+dx,player.y))player.x+=dx;if(!blocked(player.x,player.y+dy))player.y+=dy;player.dir=dx?Math.sign(dx):player.dir;player.walk+=dt; if(Math.floor(player.walk*5)!==Math.floor((player.walk-dt)*5))audio.tone(90,.025)}floaters.forEach(f=>{f.y-=10*dt;f.t-=dt});floaters=floaters.filter(f=>f.t>0)}
function loop(now:number){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);if(dialogue&&dialogue.shown<(dialogue.reaction??dialogue.enc.prompt).length){dialogue.shown+=dt*42;if(Math.floor(dialogue.shown)%4===0)audio.type();renderUI()}render();if(mode==='game'&&Math.floor(now/250)!==Math.floor((now-dt*1000)/250))renderUI();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','e'].includes(k))e.preventDefault();keys.add(k);if((k==='e'||k===' ')&&!e.repeat)interact();if(k==='escape'&&mode==='game'&&!dialogue){paused=!paused;renderUI()}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));document.querySelector('#interact')!.addEventListener('pointerdown',interact);document.querySelectorAll<HTMLButtonElement>('[data-key]').forEach(b=>{const k=b.dataset.key!;b.addEventListener('pointerdown',e=>{e.preventDefault();keys.add(k)});['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>keys.delete(k)))});menu();requestAnimationFrame(loop);
